### ISSUE TITLE
Remove flurl dependency

### ISSUE THREAD

**Issue by nozzlegear** [nozzlegear/ShopifySharp#200]
Before v4 we discussed removing all external dependencies for making web requests. I don't remember my reasoning but I decided to use Flurl instead of relying on the base HttpClient. I'm now coming to regret that :wink:. Flurl has made some recent changes where they remove the `Clone` methods on requests, a method that we rely on in ShopifySharp when repeating requests with some Execution Policies. I've also been getting a bunch of reports of broken dependencies, and have personally run into that problem as well. 

I'm working on a few changes that will completely remove Flurl and instead use the base HttpClient.

**Comment by nozzlegear** [comment]
Removed in 4.8.0 f3788aa

**Comment by clement911** [comment]
Hi @nozzlegear 

I'm a worried about this because I hit serious issues with HttpClient in the past.

If you instantiate a new HttpClient per request this is likely to create a lot of issues.
https://github.com/nozzlegear/ShopifySharp/commit/4785da63bafe58e8a3d1b5373394c024aaff4848#diff-37e30a763a8bbefb6c0addbab1a1ec7aR126

You may not experience the issue until heavy load but it will definitely happen.

The recommended pattern is to use a single static HttpClient instance.

I personally hit that issue in production and making it a static fix our problems. 

Is this something that you have considered?

Here are some resources that document the issue:
https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/
https://stackoverflow.com/questions/15705092/do-httpclient-and-httpclienthandler-have-to-be-disposed
https://stackoverflow.com/questions/11178220/is-httpclient-safe-to-use-concurrently
https://stackoverflow.com/questions/22560971/what-is-the-overhead-of-creating-a-new-httpclient-per-call-in-a-webapi-client
https://softwareengineering.stackexchange.com/questions/330364/correct-way-of-using-httpclient
http://byterot.blogspot.com.au/2016/07/singleton-httpclient-dns.html

**Comment by nozzlegear** [comment]
Thanks for the links @clement911, I wasn't aware of this behavior. I'll publish a fix for this today, and update here once it's done.

**Comment by nozzlegear** [comment]
Done in b3e9cf9! Should be available on nuget in 4.8.1 within the next 30 minutes. Thanks for the heads up @clement911!

**Comment by clement911** [comment]
No worries. Thanks again for another fast turn around.
ShopifySharp is getting really powerful!

**Comment by clement911** [comment]
A good article that explains the issue: https://blogs.msdn.microsoft.com/alazarev/2017/12/29/disposable-finalizers-and-httpclient/

**Comment by clement911** [comment]
Hi @nozzlegear I was checking your code fix but it looks like the HttpClient is still not static?
Was this a typo? The commit message said it made it static...

`private HttpClient _Client { get; } = new HttpClient();`

**Comment by clement911** [comment]
Making it a property is not enough because any time a new ShopifyService is instantiated, a new HttpClient will be instantiated.

**Comment by nozzlegear** [comment]
Oh shoot, you're right. Forgot to add the static keyword!

**Comment by nozzlegear** [comment]
Fixed in 4.8.4!

**Comment by clement911** [comment]
20 minutes turnaround. You're a machine!

**Comment by clement911** [comment]
It looks like the HttpClient is being reworked for asp.net core 2.1 so this may have to change again, although hopefully it will be a much smaller change.
https://blogs.msdn.microsoft.com/webdev/2018/02/28/asp-net-core-2-1-preview1-introducing-httpclient-factory/
